# Generated by Django 5.2.7 on 2025-11-02 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_desc', models.CharField()),
                ('recipe_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
