# Generated by Django 5.2.7 on 2025-11-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0002_vege_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='vege',
            name='recipe_view_count',
            field=models.IntegerField(default=1),
        ),
    ]
