# Generated by Django 6.0 on 2025-12-26 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0006_subject_subjectmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_report_card_generation', models.DateField(auto_created=True)),
                ('student_rank', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentreportcard', to='vegetable.student')),
            ],
            options={
                'unique_together': {('student_rank', 'date_of_report_card_generation')},
            },
        ),
    ]
