# Generated by Django 6.0 on 2025-12-28 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0008_alter_reportcard_date_of_report_card_generation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vege',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2025, 12, 28, 11, 27, 37, 381759, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
