# Generated by Django 6.0 on 2025-12-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0009_vege_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vege',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
