# Generated by Django 6.0 on 2026-04-08 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegetable', '0011_student_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vege',
            name='recipe_desc',
            field=models.CharField(max_length=500),
        ),
    ]
