# Generated by Django 6.0 on 2026-03-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
