# Generated by Django 6.0 on 2026-03-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('desc', models.TextField()),
                ('done', models.BooleanField()),
                ('created_at', models.DateTimeField()),
                ('due_date', models.DateField()),
            ],
        ),
    ]
