# Generated by Django 6.0 on 2026-03-21 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_rename_title_todo_title1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='title1',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
