# Generated by Django 6.0 on 2026-03-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_alter_todo_desc_alter_todo_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='desc',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
