# Generated by Django 6.0 on 2026-03-24 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_alter_todo_created_at_alter_todo_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
