# Generated by Django 6.0 on 2026-04-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0012_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title1',
            field=models.CharField(max_length=100),
        ),
    ]
